import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/app/theme';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import LayoutProvider from '@/shared/components/LayoutProvider';
import ProviderProps from './ProviderProps';
import { Suspense } from 'react';
import { LinearProgress } from '@mui/material';

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute='class' />
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            <CssBaseline />
            <Suspense fallback={<LinearProgress />}>
              <LayoutProvider
                navigation={ProviderProps.navigation}
                branding={ProviderProps.branding}
              >
                {props.children}
              </LayoutProvider>
            </Suspense>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
